micronaut:
    application:
        name: location-tracker
    server:
        port: -1
        host: ""
    http:
        logger-name: "HttpClient"

    user:
        type: "file"
        location: "/etc/user.json"
        default-location: "user.json"
    location-cloud:
        host: "localhost"
        port: "8086"
        apis:
            base: "http://localhost:8086/api/"
            users: "users/"
            paths: "paths/"
