micronaut:
    application:
        name: location-tracker
    user:
        type: "file"
        location: "/etc/user.json"
        default-location: "user.json"
    location-cloud:
        host: "localhost"
        port: "8086"
        apis:
            base: "${micronaut.location-cloud.host}:${micronaut.location-cloud.port}"
            users: "/api/users/"
            paths: "/api/paths/"
