spring:
  application:
    name: location-server
  data:
    postgres:
      host: ${POSTGRES_HOST}
      port: 5432
      database: 'location-server'
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

server:
  port: 9000
  connection-timeout: 1000

liquibase:
  enabled: true # enabled by default
  change-log: classpath:/liquibase/db.changelog-master.xml